<div class="c-aad-login">

  <div class="c-aad-login__content">

    <h2 class="c-aad-login__heading">
      Log in to <em><?php echo get_bloginfo('name') ?></em>
    </h2>

    <p class="c-aad-login__description c-aad-login__description--log-in">
      Use your Mercer Office 365 account to log in to WordPress:
    </p>

    <div class="c-aad-login__button-wrapper c-aad-login__button-wrapper--log-in">
      <a class="c-button c-button--log-in" href="#">
        <span class="c-button__icon">
          <svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
            <g stroke-linecap="round" stroke-width="1" fill="none" stroke-linejoin="round">
              <path d="M14.5,19.521v2.979h-13v-21h13v4"></path>
              <path d="M22.5,12.5h-17"></path>
              <path d="M10.5,7.492l-5,5l5,5"></path>
            </g>
            <path fill="none" d="M0,0h24v24h-24Z"></path>
          </svg>
        </span>
        <span class="c-button__text">
          Office 365 SSO Log In
        </span>
      </a>
    </div>

    <p class="c-aad-login__description c-aad-login__description--log-out">
      Log out everywhere you are using your Mercer Office 365 account:
    </p>

    <div class="c-aad-login__button-wrapper c-aad-login__button-wrapper--log-out">
      <a class="c-button c-button--log-out" href="#">
        <span class="c-button__icon">
          <svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
            <g stroke-linecap="round" stroke-width="1" fill="none" stroke-linejoin="round">
              <path d="M14.5,19.521v2.979h-13v-21h13v4"></path>
              <path d="M5.5,12.5h17"></path>
              <path d="M17.5,7.492l5,5l-5,5"></path>
            </g>
            <path fill="none" d="M0,0h24v24h-24Z"></path>
          </svg>
        </span>
        <span class="c-button__text">
          Office 365 SSO Log Out
        </span>
      </a>
    </div>

  </div>

</div>
