<div class="c-logged-out-follow-up">

  <div class="c-logged-out-follow-up__content">

    <h2 class="c-logged-out-follow-up__heading">
      <strong>Stop!</strong> You are still logged in to Azure AD.
    </h2>

    <p class="c-logged-out-follow-up__message">
      You just logged out of WordPress. If this is a shared computer, you might also want to log out of Azure AD.
    </p>

    <p class="c-logged-out-follow-up__invitation">
      Log out everywhere you are using your Mercer Office 365 account:
    </p>

    <div class="c-logged-out-follow-up__log-out-button-container">
      <a class="c-button c-button--log-out" href="#aad-logout">
        <span class="c-button__icon">
          <svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <!--Generated by IJSVG (https://github.com/iconjar/IJSVG)-->
            <g stroke-linecap="round" stroke-width="1" fill="none" stroke-linejoin="round">
              <path d="M14.5,19.521v2.979h-13v-21h13v4"></path>
              <path d="M5.5,12.5h17"></path>
              <path d="M17.5,7.492l5,5l-5,5"></path>
            </g>
            <path fill="none" d="M0,0h24v24h-24Z"></path>
          </svg>
        </span>
        <span class="c-button__text">
          Office 365 SSO Log Out
        </span>
      </a>
    </div>

  </div>

</div>
